### ISSUE TITLE
crashes given a noisy image

### ISSUE THREAD

**Issue by TadLeonard** [TadLeonard/crash-kiss#14]
If the foreground of the image intersects the center line and the width of the foreground area in a row is large enough, the program will crash because of a numpy-array-length-of-zero problem. We should be able to process any image (whether the result will be nice or not) without crashing.

**Comment by TadLeonard** [comment]
The typical fix is to increase the `--threshold` argument, but that shouldn't be necessary.

**Comment by TadLeonard** [comment]
Interestingly, the crash seems to happen only in `--sequence` mode.

### This crashes
`./kiss.py examples/couple_small.jpg -w /share --sequence 10 --in-parallel 1 -d 100 -t 10`

```
Traceback (most recent call last):
  File "./kiss.py", line 267, in <module>
    main()
  File "./kiss.py", line 87, in main
    run_sequence(args)
  File "./kiss.py", line 151, in run_sequence
    for img, step in image_steps:
  File "/home/tad/Downloads/share/crash_kiss/crash_kiss/crash.py", line 48, in iter_crash
    yield center_crash(img.copy(), fg, bounds), max_depth  # deepest crash
  File "/home/tad/Downloads/share/crash_kiss/crash_kiss/crash.py", line 155, in center_crash
    lmov, rmov = mov_crash(crash_data, row_data)
  File "/home/tad/Downloads/share/crash_kiss/crash_kiss/crash.py", line 226, in mov_crash
    irow[center + fg_r_start + rlen + rmov:])
ValueError: could not broadcast input array from shape (449,3) into shape (0,3)
```

### This doesn't
`./kiss.py examples/couple_small.jpg -w /share -d 100 -t 10`

### Increasing the threshold also fixes the problem
`./kiss.py examples/couple_small.jpg -w /share --sequence 10 --in-parallel 1 -d 100 -t 50`

**Comment by TadLeonard** [comment]
Revealing the foreground illustrates the problem. The crash happens when the foreground consumes the the entire selection area.

The image below was created with `./kiss.py examples/couple_small.jpg -w /share -d 100 -t 10 -e`.

![couple_small_crashed](https://cloud.githubusercontent.com/assets/6044830/6198009/220ae264-b3b6-11e4-8243-097cb01c35e5.jpg)
